.PHONY: clean All

All:
	@echo "----------Building project:[ Test_1 - Debug ]----------"
	@cd "Test_1" && "$(MAKE)" -f  "Test_1.mk"
clean:
	@echo "----------Cleaning project:[ Test_1 - Debug ]----------"
	@cd "Test_1" && "$(MAKE)" -f  "Test_1.mk" clean
